// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestArgs struct {
	Arg1                 float32  `protobuf:"fixed32,1,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2                 float32  `protobuf:"fixed32,2,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestArgs) Reset()         { *m = RequestArgs{} }
func (m *RequestArgs) String() string { return proto.CompactTextString(m) }
func (*RequestArgs) ProtoMessage()    {}
func (*RequestArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *RequestArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestArgs.Unmarshal(m, b)
}
func (m *RequestArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestArgs.Marshal(b, m, deterministic)
}
func (m *RequestArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestArgs.Merge(m, src)
}
func (m *RequestArgs) XXX_Size() int {
	return xxx_messageInfo_RequestArgs.Size(m)
}
func (m *RequestArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestArgs proto.InternalMessageInfo

func (m *RequestArgs) GetArg1() float32 {
	if m != nil {
		return m.Arg1
	}
	return 0
}

func (m *RequestArgs) GetArg2() float32 {
	if m != nil {
		return m.Arg2
	}
	return 0
}

type ResponseResult struct {
	Result               float32  `protobuf:"fixed32,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseResult) Reset()         { *m = ResponseResult{} }
func (m *ResponseResult) String() string { return proto.CompactTextString(m) }
func (*ResponseResult) ProtoMessage()    {}
func (*ResponseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ResponseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseResult.Unmarshal(m, b)
}
func (m *ResponseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseResult.Marshal(b, m, deterministic)
}
func (m *ResponseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseResult.Merge(m, src)
}
func (m *ResponseResult) XXX_Size() int {
	return xxx_messageInfo_ResponseResult.Size(m)
}
func (m *ResponseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseResult.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseResult proto.InternalMessageInfo

func (m *ResponseResult) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *ResponseResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestArgs)(nil), "message.RequestArgs")
	proto.RegisterType((*ResponseResult)(nil), "message.ResponseResult")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x46, 0x51, 0xcb, 0x70, 0xa4, 0x88, 0x25, 0x4a, 0x3a, 0x89, 0x27, 0x4f, 0x42, 0x46, 0x97,
	0x6e, 0x1e, 0x3b, 0xd4, 0x61, 0xfb, 0x05, 0xe5, 0x0e, 0x5b, 0x90, 0xad, 0xed, 0xac, 0xfd, 0xfe,
	0x70, 0xdb, 0xc2, 0xdb, 0x9b, 0x07, 0x1f, 0xbc, 0x81, 0x69, 0x83, 0x44, 0x17, 0x89, 0x45, 0xab,
	0x95, 0x51, 0x6c, 0xe2, 0xce, 0x6c, 0x07, 0x31, 0xc7, 0x57, 0x87, 0x64, 0x2a, 0x2d, 0x89, 0x31,
	0x18, 0x55, 0x5a, 0x6e, 0x12, 0x2f, 0xf5, 0x72, 0x9f, 0x5b, 0x76, 0xae, 0x4c, 0xfc, 0xbf, 0x2b,
	0xb3, 0x13, 0xcc, 0x38, 0x52, 0xab, 0x9e, 0x84, 0x1c, 0xa9, 0x7b, 0x18, 0xb6, 0x84, 0xf0, 0x4b,
	0x6e, 0xeb, 0xae, 0x7e, 0x5d, 0x2b, 0x81, 0x76, 0x3d, 0xe6, 0x96, 0xd9, 0x1c, 0x82, 0x86, 0x64,
	0x12, 0xa4, 0x5e, 0x1e, 0xf1, 0x1e, 0xcb, 0x03, 0xc4, 0x47, 0x34, 0xb7, 0x33, 0xea, 0xf7, 0xbd,
	0x46, 0xb6, 0x87, 0xa8, 0x12, 0xa2, 0x37, 0x4a, 0xb0, 0x45, 0xf1, 0x6b, 0x1f, 0x94, 0xae, 0x57,
	0x03, 0x3b, 0x0c, 0xb9, 0x86, 0xf6, 0xc3, 0xed, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x14, 0xd9,
	0xcc, 0xf2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MethServiceClient is the client API for MethService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MethServiceClient interface {
	AddMethod(ctx context.Context, in *RequestArgs, opts ...grpc.CallOption) (*ResponseResult, error)
}

type methServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMethServiceClient(cc grpc.ClientConnInterface) MethServiceClient {
	return &methServiceClient{cc}
}

func (c *methServiceClient) AddMethod(ctx context.Context, in *RequestArgs, opts ...grpc.CallOption) (*ResponseResult, error) {
	out := new(ResponseResult)
	err := c.cc.Invoke(ctx, "/message.MethService/AddMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MethServiceServer is the server API for MethService service.
type MethServiceServer interface {
	AddMethod(context.Context, *RequestArgs) (*ResponseResult, error)
}

// UnimplementedMethServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMethServiceServer struct {
}

func (*UnimplementedMethServiceServer) AddMethod(ctx context.Context, req *RequestArgs) (*ResponseResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMethod not implemented")
}

func RegisterMethServiceServer(s *grpc.Server, srv MethServiceServer) {
	s.RegisterService(&_MethService_serviceDesc, srv)
}

func _MethService_AddMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethServiceServer).AddMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.MethService/AddMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethServiceServer).AddMethod(ctx, req.(*RequestArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _MethService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MethService",
	HandlerType: (*MethServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMethod",
			Handler:    _MethService_AddMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
