// Code generated by protoc-gen-go. DO NOT EDIT.
// source: human.proto

package human

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Man int32

const (
	Man_male   Man = 0
	Man_female Man = 1
)

var Man_name = map[int32]string{
	0: "male",
	1: "female",
}

var Man_value = map[string]int32{
	"male":   0,
	"female": 1,
}

func (x Man) String() string {
	return proto.EnumName(Man_name, int32(x))
}

func (Man) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9e3dc48d8ad867e8, []int{0}
}

func init() {
	proto.RegisterEnum("Man", Man_name, Man_value)
}

func init() {
	proto.RegisterFile("human.proto", fileDescriptor_9e3dc48d8ad867e8)
}

var fileDescriptor_9e3dc48d8ad867e8 = []byte{
	// 68 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x28, 0xcd, 0x4d,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x92, 0xe6, 0x62, 0xf6, 0x4d, 0xcc, 0x13, 0xe2,
	0xe0, 0x62, 0xc9, 0x4d, 0xcc, 0x49, 0x15, 0x60, 0x10, 0xe2, 0xe2, 0x62, 0x4b, 0x4b, 0x05, 0xb3,
	0x19, 0x93, 0xd8, 0xc0, 0x6a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xc1, 0x6b, 0xe0,
	0x32, 0x00, 0x00, 0x00,
}
