// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from order.proto</summary>
public static partial class OrderReflection {

  #region Descriptor
  /// <summary>File descriptor for order.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OrderReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtvcmRlci5wcm90byI5CgVPcmRlchIQCghvcmRlcl9pZBgBIAEoCRILCgNu",
          "dW0YAiABKAMSEQoJdGltZXN0YW1wGAMgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Order), global::Order.Parser, new[]{ "OrderId", "Num", "Timestamp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Order : pb::IMessage<Order> {
  private static readonly pb::MessageParser<Order> _parser = new pb::MessageParser<Order>(() => new Order());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Order> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::OrderReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Order() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Order(Order other) : this() {
    orderId_ = other.orderId_;
    num_ = other.num_;
    timestamp_ = other.timestamp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Order Clone() {
    return new Order(this);
  }

  /// <summary>Field number for the "order_id" field.</summary>
  public const int OrderIdFieldNumber = 1;
  private string orderId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string OrderId {
    get { return orderId_; }
    set {
      orderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 2;
  private long num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 3;
  private int timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Order);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Order other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (OrderId != other.OrderId) return false;
    if (Num != other.Num) return false;
    if (Timestamp != other.Timestamp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (OrderId.Length != 0) hash ^= OrderId.GetHashCode();
    if (Num != 0L) hash ^= Num.GetHashCode();
    if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (OrderId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(OrderId);
    }
    if (Num != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Num);
    }
    if (Timestamp != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Timestamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (OrderId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderId);
    }
    if (Num != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Num);
    }
    if (Timestamp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Timestamp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Order other) {
    if (other == null) {
      return;
    }
    if (other.OrderId.Length != 0) {
      OrderId = other.OrderId;
    }
    if (other.Num != 0L) {
      Num = other.Num;
    }
    if (other.Timestamp != 0) {
      Timestamp = other.Timestamp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          OrderId = input.ReadString();
          break;
        }
        case 16: {
          Num = input.ReadInt64();
          break;
        }
        case 24: {
          Timestamp = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
